databases:
  - name: dadospacientes
    databaseName: dadospacientes
    user: dadospacientes_user
    ipAllowList: []
    
services:
  - type: web
    name: envio email automatico
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: RAILS_MASTER_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: dadospacientes
          property: connectionString
  - type: redis
    name: redis
    ipAllowList: []
    plan: free